networks:
  mnestix-network:
    driver: bridge
    name: mnestix-network

services:
  mnestix-proxy:
    container_name: mnestix-proxy
    image: mnestix-proxy:dev
    build:
      dockerfile: Dockerfile
    ports:
      - '5065:5065'

  mnestix-aas-generator:
    ports:
      - '5064:5064'

  aas-environment:
    ports:
      - '8081:8081'

  basyx-db:
    ports:
      - '5432:5432'